function [log_p] = log_X_not_included(X_not_incl, X_incl, h_gamma, k_0, delta_c)
  p_not_gamma = size(X_not_incl, 2);
  n = size(X_incl, 1);
  Sigma = eye(n) + h_gamma * (X_incl * X_incl');
  Psi = eye(p_not_gamma) + 1 / k_0 * X_not_incl' / Sigma * X_not_incl;
  
  log_p = logMvGamma((delta_c + n) / 2, p_not_gamma) - ...
      logMvGamma(delta_c / 2, p_not_gamma) - ...
      n * p_not_gamma / 2 * log(pi * k_0) - ...
      p_not_gamma / 2 * logdet(Sigma) - ...
      (delta_c + n) / 2 * logdet(Psi);
end